User/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.user,name='User'),
    path('FormularioRegistro/', views.formularioRegistro, name="register"),
    path('modificarUser/<id>/', views.modificarUser, name='modificarUser'),
    path('eliminarUser/<id>/', views.eliminarUser, name='eliminarUser'),
]

animanwiki/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('Inicio.urls')),
    path('Naruto/', include('Naruto.urls')),
    path('ListaPersonajes/', include('ListaPersonajes.urls')),
    path('User/', include('User.urls')),
    path('search/', include('search.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

Naruto/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances


# Create your models here.

class Informaciones(models.Model):
	"""Model representing an author."""
	Nombre = models.CharField(max_length=100)
	Apellido = models.CharField(max_length=100)
	imagen = models.ImageField(upload_to='images')

	class Meta:
		ordering = ['Apellido', 'Nombre']


	def __str__(self):
		"""String for representing the Model object."""
		return f'{self.Nombre} {self.Apellido}'	

search/models.py
from django.db import models

# Create your models here.

search/views.py
import requests

from isodate import parse_duration

from django.conf import settings
from django.shortcuts import render, redirect

def index(request):
    videos = []

    if request.method == 'POST':
        search_url = 'https://www.googleapis.com/youtube/v3/search'
        video_url = 'https://www.googleapis.com/youtube/v3/videos'

        search_params = {
            'part' : 'snippet',
            'q' : request.POST['search'],
            'key' : settings.YOUTUBE_DATA_API_KEY,
            'maxResults' : 12,
            'type' : 'video'
        }

        r = requests.get(search_url, params=search_params)

        results = r.json()['items']

        video_ids = []
        for result in results:
            video_ids.append(result['id']['videoId'])

        if request.POST['submit'] == 'lucky':
            return redirect(f'https://www.youtube.com/watch?v={ video_ids[0] }')

        video_params = {
            'key' : settings.YOUTUBE_DATA_API_KEY,
            'part' : 'snippet,contentDetails',
            'id' : ','.join(video_ids),
            'maxResults' : 12
        }

        r = requests.get(video_url, params=video_params)

        results = r.json()['items']

        
        for result in results:
            video_data = {
                'title' : result['snippet']['title'],
                'id' : result['id'],
                'url' : f'https://www.youtube.com/watch?v={ result["id"] }',
                'duration' : int(parse_duration(result['contentDetails']['duration']).total_seconds() // 60),
                'thumbnail' : result['snippet']['thumbnails']['high']['url']
            }

            videos.append(video_data)

    context = {
        'videos' : videos
    }
    
    return render(request, 'search/index.html', context)

search/templates/search/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Busqueda en Youtube</title>
    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/busqueda.css' %}" rel="stylesheet">
  </head>
  <body>

<main role="main">
	
	     <header>
            <nav>
               <ul>
                <li><a class="menu" href="{% url 'Inicio' %}">Inicio</a></li>
                <li><a class="menu" href="{% url 'Naruto' %}">Personajes</a></li>
                <li><a class="menu" href="{% url 'ListaPersonajes' %}">Galeria</a></li>
                {% if user.is_authenticated %}
                {% if perms.Naruto.delete_informaciones %}
                <li><a class="menu" href="{% url 'admin:index' %}">Administrar</a></li>
                {% endif %}                
                <li><a class="menu" href="{% url 'User' %}">{{ user.username }}</a></li>
                <li><a class="menu" href="{% url 'logout' %}">Cerrar Sesión</a></li>
                {% else %}
                <li><a class="menu" href="{% url 'register' %}">Registro</a></li>
                <li><a class="menu" href="{% url 'login' %}">login</a></li>
                {% endif %}
              </ul>
      </nav> 
    </header>

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Búsqueda Youtube</h1>
      <p class="sub">Muestra los mejores 12 resultados de búsqueda</p>
      <form method="POST">
      <div class="input-group mb-3">
          {% csrf_token %}
          <input type="text" name="search" class="form-control" aria-label="Username">
      </div>
      <p>
        <button type="submit" name="submit" value="search" class="btn btn-primary my-2">Buscar</button>
        <button type="submit" name="submit" value="lucky" class="btn btn-secondary my-2">Me siento con suerte</button>
      </p>
      </form>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for video in videos %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ video.thumbnail }}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"></img>
            <div class="card-body">
              <p class="card-text">{{ video.title }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a type="button" href="{{ video.url }}" class="btn btn-sm btn-outline-secondary">Ver</a>
                </div>
                <small class="text-muted">{{ video.duration }} mins</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

</main>
</body>
</html>